---
openapi: 3.1.0
info:
  title: HelloWorld API
  version: 1.0.0
  info:
    description: |
      This is a sample server.
      # Introduction
      This is only a sample server. Consider this as a playground to test your API.
paths:
  "/api/helloworld":
    get:
      summary: Get a hello world message
      responses:
        '200':
          description: A hello world message
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
  "/graphql/helloworld":
    post:
      summary: Get a hello world message via GraphQL
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                query:
                  type: string
      responses:
        '200':
          description: A hello world message
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: object
                    properties:
                      helloWorld:
                        type: string
